trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: InstallAndBuild
  displayName: 'Install and Build'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

- job: CodeAnalysis
  displayName: 'Code Analysis'
  dependsOn: InstallAndBuild
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      npm run lint
    displayName: 'Run Code Analysis'

- job: SaveArtifacts
  displayName: 'Save Build Artifacts'
  dependsOn: InstallAndBuild
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/dist'
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Files to Artifact Staging Directory'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
    displayName: 'Publish Build Artifacts'

- job: Deploy
  displayName: 'Deploy'
  dependsOn: SaveArtifacts
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo "Deploying..."
    displayName: 'Deploy Step'
